#!/bin/bash

if [ "$EUID" -ne 0 ]
    then echo "You need to be root to run this script."
    exit 1
fi

DIR='/etc/puppetlabs/code'
ENVIRONMENT='production'
/opt/puppetlabs/bin/puppet apply --environment=$ENVIRONMENT $DIR/environments/$ENVIRONMENT/manifests "$@"
