#!/bin/bash

if [ "$EUID" -ne 0 ]
    then echo "You need to be root to run this script."
    exit 1
fi

DIR='/etc/puppetlabs/code'
ENVIRONMENT='production'
PUPPETBIN=$(which puppet || echo '/opt/puppetlabs/bin/puppet')

${PUPPETBIN} apply --environment=$ENVIRONMENT $DIR/environments/$ENVIRONMENT/manifests "$@"
