#!/bin/bash
DIR="$( dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" )"

if [ "$EUID" -ne 0 ]
    then echo "You need to be root to run this script."
    exit 1
fi

function get_distro_name {
    if [[ -r '/etc/lsb-release' ]]; then
        . /etc/lsb-release
        [[ "$DISTRIB_ID" ]] && n="$DISTRIB_ID"
    elif [[ -r '/etc/release' ]]; then
        n="head -1 /etc/release | sed 's/ *\([[^0-9]]*\) [0-9].*/\1/'"
    elif [[ -r '/etc/arch-release' ]]; then
        n="Arch Linux"
    elif [[ -r '/etc/debian_version' ]]; then
        n='Debian'
    elif [[ -r '/etc/gentoo-release' ]]; then
        n='Gentoo'
    elif [[ -r '/etc/knoppix-version' ]]; then
        n='Knoppix'
    elif [[ -r '/etc/mandrake-release' ]]; then
        n='Mandrake'
    elif [[ -r '/etc/pardus-release' ]]; then
        n='Pardus'
    elif [[ -r '/etc/puppyversion' ]]; then
        n='Puppy Linux'
    elif [[ -r '/etc/redhat-release' ]]; then
        n='Red Hat'
    elif [[ -r '/etc/sabayon-release' ]]; then
        n='Sabayon'
    elif [[ -r '/etc/slackware-version' ]]; then
        n='Slackware'
    elif [[ -r '/etc/SuSE-release' ]]; then
        n='SuSE'
    elif [[ -r '/etc/xandros-desktop-version' ]]; then
        n='Xandros'
    elif [[ -r '/etc/zenwalk-version' ]]; then
        n="Zenwalk"
    fi
    [[ "${n:-}" = '' ]] && echo "ERROR: Could not determine the distro name" >&2 && exit 1

    echo $n
} # get_distro_name


DISTRO=$(get_distro_name)

case "$DISTRO" in
    "Red Hat")
        rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
        yum install -y puppet-agent
        ;;
    "Debian")
        wget https://apt.puppetlabs.com/puppetlabs-release-pc1-jessie.deb
        dpkg -i puppetlabs-release-pc1-jessie.deb
        rm -f puppetlabs-release-pc1-jessie.deb
        apt-get update
        apt-get install -y puppet-agent
        ;;
    *)
        echo "ERROR: Distribution ${DISTRO} not supported" >&2 && exit 1
        ;;
esac

rm -rf /etc/puppetlabs/code
ln -s "${DIR}/code" /etc/puppetlabs/code

rm -rf /etc/puppetlabs/puppet
ln -s "${DIR}/code" /etc/puppetlabs/puppet
