#!/bin/bash

if [ "$EUID" -ne 0 ]
    then echo "You need to be root to run this script."
    exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

"${DIR}/install_puppet"

rm -rf /etc/puppetlabs/code
ln -s "${DIR}/../code" /etc/puppetlabs/code

rm -rf /etc/puppetlabs/puppet
ln -s "${DIR}/../puppet" /etc/puppetlabs/puppet
